version: '3'
services:
  mc-mapgen:
    image: mc-mapgen
    container_name: mc-mapgen
    volumes:
      - "${MAPLOCATION}:/mc:z"
      - webcont:/webcont
  mc-mapgen-lighttpd:
    image: mc-mapgen-lighttpd
    container_name: mc-mapgen-lighttpd
    volumes:
      - webcont:/var/www/html/webcont
    environment:
      PORT: 8888
      SERVER_NAME: localhost
      SERVER_ROOT: /var/www/html
    ports:
      - "8888:8888"
volumes:
  webcont:
